### ISSUE TITLE
List of Keyboard shortcuts

### ISSUE THREAD

**Issue by nakchak** [icsharpcode/RefactoringEssentials#133]
Loving this extension, have sucessfully moved away from the bloat of Resharper after many years :)
One thing i'm struggling with is finding keyboard shortcuts for refactoring essentials.  
Does anyone have a list?

I think i have found "Ctrl + ." to open the analyzer context menu when on the line with the issue, is there equivalents to Resharper's "Alt + Page Up" and "Alt + Page Down" to navigate between detected issues or a way to remap the shortcuts so i don't have to retrain myself to a new set of chords?

As a feature request a Refactoring essentials for resharper converts guide would be really handy or just a resharper keyboard map

**Comment by Rpinski** [comment]
Refactoring Essentials doesn't offer special key shortcuts, but you can use Visual Studio's built-in commands. `Ctrl+.` is one of them (shows the bulb menu). Since all issues are shown in "Error List" view, you can define your own shortcuts for navigating through them. Just go to

*"Tools" -> "Options..." -> "Environment" -> "Keyboard"*

and define key shortcuts for the commands "View.PreviousError" and "View.NextError".
