### ISSUE TITLE
Error when trying to create an event invocator

### ISSUE THREAD

**Issue by ddobrev** [icsharpcode/RefactoringEssentials#191]
I have a Monodroid project and I have a private class with public events nested in an activity. When I try creating an event invocator for any of the events, I get an error (that message that pops above the open file, with the two buttons "Enable" and "Enable and ignore future errors").

Visual Studio 2015 Update 1
Other extensions: https://github.com/jzoss/Git-Source-Control-Provider, PostSharp, NUnit Test Adapter and, of course, Xamarin
Windows 7 64-bit

If you keep a log, let me know its location so that I can send it too.

**Comment by ddobrev** [comment]
[ActivityLog.zip](https://github.com/icsharpcode/RefactoringEssentials/files/180038/ActivityLog.zip)

Log attached. There are 3 entries for "CreateEventInvocatorCodeRefactoringProvider" which are about the bug.

**Comment by ddobrev** [comment]
Thank you. When can I expect an update containing this fix?

**Comment by Rpinski** [comment]
Should be in next release (4.0), which we intend to release as soon as VS 2015 Update 2 is final. Or try the development build on [VSIXGallery](http://vsixgallery.com/extension/NR6Pack.Refactorings.Vsix..cd27e59b-5c56-4238-8931-c9bb745a7a7f/) (requires VS 2015 Update 2 RC).

I hope I've really covered your case, since I don't know which source code this exception has been thrown with. Do you have event handlers with only one parameter in your solution?

**Comment by ddobrev** [comment]
@Rpinski as a matter of fact, yes, I had this event:

public event Action<Intent> Finished;

I found it cumbersome to extend EventArgs while at the same time EvenHandler<> requires it. So I decided now that I had to use Action anyway, I might skip the sender as well. I decided to share these details because having seem many other API-s use such events, I think the fix is general rather than specific to my case.
My apologies for not adding a code sample to begin with, it didn't cross my mind. I'll remember next time. And there will be a next time because I've seen the pop-up at other fixes. :)
