### ISSUE TITLE
Insert await code issue refinements

### ISSUE THREAD

**Issue by Therzok** [icsharpcode/RefactoringEssentials#218]
Given a method which causes this issue:
```
bool MyMethod ()
{
    GetBoolAsync();
}
```

We have an option to insert await on GetBoolAsync().

That does not compile afterwards - the code issue fix should also import `System.Threading.Tasks` and convert MyMethod to be `async Task<bool>`.

**Comment by Rpinski** [comment]
But you speak about the fix for

*"CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call."*,

right? That fix doesn't come from Refactoring Essentials, at all. Seems to be this one: https://github.com/dotnet/roslyn/blob/56f605c41915317ccdb925f66974ee52282609e7/src/Features/CSharp/Portable/CodeFixes/Async/CSharpAddAwaitCodeFixProvider.cs

**Comment by Therzok** [comment]
Okay, that seems like that's it, you're right!
