### ISSUE TITLE
Parameter can't be resolved for "ArgumentException"

### ISSUE THREAD

**Issue by FickoDeLux** [icsharpcode/RefactoringEssentials#227]
I have:
```c#
public override object CreateInstance(ITypeDescriptorContext context, IDictionary propertyValues)
{
     throw new ArgumentException("Invalid property values", "CreateInstance");
}
```
and get "Parameter 'CreateInstance' can't be resolved"
I am not sure this should be a feature req. or a missing implementation.

Likewise for:
```c#
public virtual object Renderer
{
	get
	{
		return _renderer;
	}
	set
	{
		if (value == null)
		{
			throw new ArgumentNullException("Renderer", "WinFormsExtenderControl");
		}
		_renderer = value;
	}
}
```

**Comment by Rpinski** [comment]
Well, strictly speaking that's a misuse of the exception constructor's parameter. See [MSDN](https://msdn.microsoft.com/en-us/library/sxykka64%28v=vs.110%29.aspx):

> *paramName*
> Type: System.String
> The name of the parameter that caused the current exception. 

So in my opinion the analyzer is right. In your 1st example you should use `propertyValues` instead of `CreateInstance` and in your 2nd example `value` instead of `WinFormsExtenderControl`.

**Comment by FickoDeLux** [comment]
Allright, thank You got it.
