### ISSUE TITLE
Configuration options?

### ISSUE THREAD

**Issue by vurso** [icsharpcode/RefactoringEssentials#254]
Hi, is there a way of configuring this awesome extensions?

I want to turn off or control some warnings for example which appear with red underlines obviously I don't want to see those in red that will make me panic and drink more coffee.

Thanks,

v

**Comment by Rpinski** [comment]
This is possible using Visual Studio's [Custom Rule Sets](https://github.com/icsharpcode/RefactoringEssentials/wiki/Custom-Rule-Sets-for-Analyzers). Instead of turning the especially stressing analyzers off you can reduce their warning level from "Error" to "Warning", for example.

**Comment by Rpinski** [comment]
I'll close this issue now, if you have further questions, feel free to ask here.

**Comment by dstj** [comment]
I know this issue is closed, but I just installed the extension and cannot see the "Open Active Rule Set" mentioned in the aforementioned [wiki link](https://github.com/icsharpcode/RefactoringEssentials/wiki/Custom-Rule-Sets-for-Analyzers)...

![image](https://user-images.githubusercontent.com/467692/41294855-0cf1308e-6e27-11e8-9fd2-ad3a5f5789e0.png)

Using Visual Studio 2017 Community 15.7.3 and my project is a .NET Core 2.1.300 project.
