### ISSUE TITLE
Add null check for parameter must be changed

### ISSUE THREAD

**Issue by mynkow** [icsharpcode/RefactoringEssentials#75]
Checks for null must be done always with ReferenceEquals(object x, object y) because overrides of operators is not a runtime operation but a compile time.

Current: if(obj == null) throw new ArgumentNullException(nameof(obj));
Should be if(ReferenceEquals(null, obj)) throw new ArgumentNullException(nameof(obj));

https://msdn.microsoft.com/en-us/library/system.object.referenceequals(v=vs.110).aspx

https://github.com/icsharpcode/RefactoringEssentials/blob/bb25d62f8610d863a3bc639dc1924585bf4373c9/RefactoringEssentials/CSharp/CodeRefactorings/Synced/CheckIfParameterIsNullCodeRefactoringProvider.cs

**Comment by Rpinski** [comment]
I don't think this is really necessary. ``ReferenceEquals`` doesn't have such a big advantage (for the null check case) that is worth the worse readability.

For example see:
http://stackoverflow.com/questions/12465961/is-referenceequalsmyobject-null-better-practice-than-myobject-null

**Comment by mynkow** [comment]
It is not about advantage. It is about correct code.

class Program
    {
        static void Main(string[] args)
        {
            Foo foo = null;
            //if (ReferenceEquals(null, foo)) // Will throw ArgumentNullException
            //    throw new ArgumentNullException();
            if (foo == null) // Will throw NullReferenceException
                throw new ArgumentNullException();
        }
    }

    public class Foo
    {
        public static bool operator ==(Foo left, Foo right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(Foo left, Foo right)
        {
            return !(left == right);
        }
    }

**Comment by Rpinski** [comment]
Yes, I know that could happen, but one might also argue that such an implementation of ``operator==`` is wrong, because it doesn't handle ``null`` (assuming that ``Foo`` is a reference type). See also:

https://msdn.microsoft.com/en-us/library/dd183755.aspx
https://msdn.microsoft.com/en-US/library/ms173147%28v=vs.90%29.aspx

Why should the refactoring produce less readable code because of the possibility that somewhere else the implementation has been done incorrectly?

**Comment by mynkow** [comment]
Again, it is not about readability or advantage or whatever.

The implementation of Equals in the System.Object universal base class also performs a reference equality check, but it is best not to use this because, if a class happens to override the method, the results might not be what you expect. The same is true for the == and != operators. When they are operating on reference types, the default behavior of == and != is to perform a reference equality check. However, derived classes can overload the operator to perform a value equality check. To minimize the potential for error, it is best to always use ReferenceEquals when you have to determine whether two objects have reference equality.

https://msdn.microsoft.com/en-us/library/Dd183759.aspx

**Comment by Rpinski** [comment]
But here we don't determine reference equality of two objects, but we compare an object with ``null``. Even if somebody overrides ``operator==`` to do a value equality check, a comparison of ``foo == null`` should return ``true``, if value of ``foo`` represents ``null``, or should return ``false`` otherwise (see.NET's ``Nullable<T>`` as an example). Any other implementation wouldn't make any practical sense in my opinion.

**Comment by mynkow** [comment]
It is exactly reference equality between an object and null.

I hope you never run into my situation to find out that `ReferenceEquals(...)` is the better approach.

**Comment by mynkow** [comment]
@Rpinski I hope this changes your opinion

https://www.youtube.com/watch?v=M0hdrybOKJg&feature=youtu.be&t=1971

**Comment by AlexPlom** [comment]
With the new "foo is null" both readability and function are improved. Would be great to see this change
